"""
Constantes utilizadas no fluxo de consulta do Mind7.
"""

CAPTCHA_RESULT = "CAPTCHA"

DOCUMENT_NOT_FOUND_VALUE = "Não encontrado"
QUERY_ERROR_VALUE = "Erro"
EMPTY_DOCUMENT_VALUE = ""

CAPTCHA_ERROR_MESSAGES = {
    "NÃO FOI POSSÍVEL VALIDAR SUA CONSULTA",
    "NAO FOI POSSIVEL VALIDAR SUA CONSULTA",
}

OWNER_SECTION_KEYWORD = "PROPRIETÁRIO"

MAX_RETRY_WAIT_SECONDS = 120
RETRY_BATCH_SIZE = 3