"""
Constantes relacionadas aos processos da automação.
"""

TRACERS_STEP_NAME = "Extração de placas do Tracers"
MIND7_STEP_NAME = "Consulta de CPFs/CNPJs no Mind7"
SCREEN_PROGRESS_PATTERN = r"Tela\s+(\d+)/(\d+)"
CPF_QUERY_PATTERN = r"Consultando placa:"

STREAMLIT_PORT = 8501
MONITOR_INITIAL_DELAY_SECONDS = 20
MONITOR_CHECK_INTERVAL_SECONDS = 10

MIN_PROGRESS_PERCENT = 5
MAX_RUNNING_PROGRESS_PERCENT = 99
MAX_CPF_PROGRESS_PERCENT = 95
CPF_PROGRESS_STEP_PERCENT = 5
FINISHED_PROGRESS_PERCENT = 100


STEP_ERROR_STATE_KEYS = {
    TRACERS_STEP_NAME: "tracers_step_error",
    MIND7_STEP_NAME: "consultation_step_error",
}